#!/usr/bin/env bash
# install and configure HAProxy

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6


sudo apt-get install -y haproxy=2.6.\*

echo "
frontend myfrontend
        bind *:80
        default_backend myservers
backend myservers
        balance roundrobin
        server 145852-web-01 34.224.1.89:80 check
        server 145852-web-02 3.94.185.231:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart

