#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop
#  except the 9th iteration which displays "Hi".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
